### ISSUE TITLE
Route to create IPLD DAG objects

### ISSUE THREAD

**Issue by dholms** [fission-suite/web-api#102]
# Summary

## Problem

Directories currently can't be added via the web-api

### Impact

Can't upload and pin any websites that are more complex than a single `index.html`

## Solution

Two options:
1. Add a route for creating ipld dag objects (the equivalent of `ipfs dag put`). This puts the burden on the client to upload a bunch of files in parallel and then link them by creating dag objects
2. Add ability to do recursive adds. This would involve uploading either a directory or FormData in a POST request and then doing the recursive add server-side. Simpler UX, but less flexibility

We'll probably want both options in the long run, but I think for now we can just stick with the dag put route.

**Comment by expede** [comment]
> Simpler UX, but less flexibility

@dholms can you delve into what we lose with this option?

**Comment by dholms** [comment]
@expede sure thing. 

Option 2 is definitely much simpler on the client side since it just requires a single POST request

Option 1 allows for arbitrary interaction with ipld objects so it's more flexible. This isn't necessary for our current use case (`ipfs-deploy`), but could be useful down the line for creating more complex IPLD structures (with hashes from other domains: eth, btc, git, etc)
The downside of option 1 is we have to send upload each file and then create a dag object for each directory, so the client side code would end up being more complex

I don't have a strong opinion on which option we go with. Option 2 keeps the `ipfs-deploy` code simpler and more similar to the other deploy scripts they have (ie pinata). So I actually have a slight preference for that one. I was treating option 1 as the default option since you're more familiar with the web-api and it sounded like you had a preference for parallelized requests. Probably just a misunderstanding :slightly_smiling_face:

**Comment by expede** [comment]
@dholms okay, cool, thanks for clarifying 😃 Yeah, my apparent preference for parallel requests was mainly "sounds quick & dirty, and the server can totally do that without breaking a sweat".

**Comment by expede** [comment]
Okay, chatted over video 📺

We're going with _Option 1_.

I'll type up what's required for the web-api side, and that may be a really good first feature for @dholms (🐦🐦🥌)

**Comment by expede** [comment]
FYI: I'm writing adding the instructions to the appropriate sections of the [GitBook HS for TS guide](https://app.gitbook.com/@runfission/s/haskell-for-typescript-devs/).
