### ISSUE TITLE
To kick off DNS propagation we should push a blank page on register

### ISSUE THREAD

**Issue by bechurch** [fission-suite/web-api#163]
NB: Feature requests will only be considered if they solve a pain

# Summary

## Problem
Currently DNS can take a while to propogate the first time after fission up / watch.

### Impact
Slow time to a live site

## Solution
Push a page at the time of register to get a head start on this delay.

# Details
It would be nice to have a default page thats prettier than a "hello world" perhaps a tutorial or a random gift

**Comment by dholms** [comment]
Added here and forgot to close: https://github.com/fission-suite/web-api/pull/165
