### ISSUE TITLE
Fission Logout

### ISSUE THREAD

**Issue by bechurch** [fission-suite/web-api#167]
NB: Feature requests will only be considered if they solve a pain

# Summary

## Problem
Its a pain to delete dotfiles. Lets do it for our users when they want to log out

### Impact
A single command logout to make it easier to switch accounts

## Solution
a cli command `fission logout` that runs `rm ~/.fission.yaml`

**Comment by expede** [comment]
https://github.com/fission-suite/web-api/pull/170
