### ISSUE TITLE
Logging with Sentry

### ISSUE THREAD

**Issue by expede** [fission-suite/web-api#179]
# Summary

## Problem

Logs with `nohup.out` are... insufficient. They're very easy to overwrite, we have to SSH in the server to read them, searching logs with `grep` leaves a lot to be desired.

## Solution

Integrate Sentry

# Detail

* Cookbook Guide: https://docs.servant.dev/en/stable/cookbook/sentry/Sentry.html
* Library: http://hackage.haskell.org/package/raven-haskell

**Comment by expede** [comment]
This feels like a @bechurch task (based of previous interest), but doesn't have to be

**Comment by bechurch** [comment]
am interested!

**Comment by expede** [comment]
WIP — actually have it working, but need to clean up the branch and not have the key hard coded (hence no pushed branch :P)
