### ISSUE TITLE
Switch from SQLite to RDS PostgreSQL

### ISSUE THREAD

**Issue by expede** [fission-suite/web-api#35]
# Problem
SQLite doesn't work well at high scale

# Solution
A. Dogfood IPFS: move database to an IPFS-backed data store
B. RDS: Switch to PostgreSQL and hook into AWS RDS when we migrate

**Comment by expede** [comment]
Okay, we're going to go with AWS RDS Postgres mainly because as a managed instance, they make it easy to do database snapshots, they keep it up to date for us, &c. The AWS console is super painful and it's a bit more expensive, but I'd rather have the DB stay up.

We're going to need to do a data migration, and change at least the `MonadSelda` instance, which is currently fixed to `Database.Selda.SQLite`.

**Comment by expede** [comment]
The main reason for changing this now is that we're having issues with SQLite and true multithreading. SQLite works great with virtual threads, but we're seeing resource contention with hardware threads. Looks like they're having the same issue over at Pantry, where they wrote a little thread blocker. Let's just use a DB that supports true concurrency.

**Comment by expede** [comment]
<img width="263" alt="Screen Shot 2019-09-19 at 08 46 54" src="https://user-images.githubusercontent.com/1052016/65259771-16096f00-daba-11e9-8953-9df4de4e1b87.png">

https://www.stackage.org/haddock/lts-14.6/selda-postgresql-0.1.8.0/Database-Selda-PostgreSQL.html

**Comment by dholms** [comment]
WIP over here: https://github.com/fission-suite/web-api/tree/postgres

**Comment by expede** [comment]
Configured security groups successfully 👍
