### ISSUE TITLE
WordPress Plugin

### ISSUE THREAD

**Issue by expede** [fission-suite/web-api#44]
# Problem

We need access to large existing markets/user bases

# Solution

* Provide a hook into Wordpress ([~30% of the internet](https://venturebeat.com/2018/03/05/wordpress-now-powers-30-of-websites/))

**Comment by expede** [comment]
@bmann is the WIP or done?

**Comment by bmann** [comment]
@expede I think probably this is backlog at best. Don’t need to track it, not actively looking for an integrator right now. Will close.
