### ISSUE TITLE
Documentation / walkthrough

### ISSUE THREAD

**Issue by expede** [fission-suite/web-api#60]
# Problem

We have no documentation aside from the [Swagger docs](https://runfission.com/docs). They're a great _reference_, but not the best for learning. It's difficult to dive into building apps purely with the abstract RESTful API.

# Solution

Write an in-depth guide in the Fission Guide on [GitBook](https://app.gitbook.com/@runfission/s/fission-docs/~/drafts/-Lqv1e_ICgykylnjrY6I/primary/) / [GitHub](https://github.com/fission-suite/fission-guide)

https://github.com/fission-suite/fission-guide

## Related Issues

* #61

**Comment by dholms** [comment]
https://app.gitbook.com/@runfission/s/fission-guide/
